{{- if .Values.caCert }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snyk-broker.fullname" . }}-cacert-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
data:
{{ (.Files.Glob .Values.caCert).AsConfig | nindent 2 }}
{{- end }}