{{- if .Values.enableCodeAgent }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.scmType}}-code-agent"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-ca
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-ca
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-ca
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "snyk-broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: code-agent
          resources:
            limits:
              cpu: {{ .Values.caResources.limits.cpu }}
              memory: {{ .Values.caResources.limits.memory }}
            requests:
              cpu: {{ .Values.caResources.requests.cpu }}
              memory: {{ .Values.caResources.requests.memory}}
          securityContext:
            {{- toYaml .Values.securityContextCa | nindent 12 }}
          image: "{{ .Values.image.caRepository }}:{{ .Values.caImage}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.container.caSnykPort }}
          {{- if or  .Values.caCert .Values.httpsCert .Values.httpsKey  }}   
          volumeMounts:
              {{- if .Values.caCert }}
              - name: {{ include "snyk-broker.fullname" . }}-cacert-volume
                mountPath: /home/node/cacert
                readOnly: true
              {{- end }}
              {{- if .Values.httpsCert }}
              - name: {{ include "snyk-broker.fullname" . }}-httpscert-volume
                mountPath: /home/node/httpscert
                readOnly: true
              {{- end }}
              {{- if .Values.httpsKey }}
              - name: {{ include "snyk-broker.fullname" . }}-httpskey-volume
                mountPath: /home/node/httpskey
                readOnly: true
              {{- end }}              
          {{- end }}
          env:
            - name: PORT
              value: {{ .Values.deployment.container.caSnykPort | squote }}
            - name: SNYK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: snyk-token
                  key: snyk-token-key
         {{- if .Values.tlsRejectUnauthorized  }}
         # Troubleshooting - Set to 0 for SSL inspection testing
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
         {{- end }}

         {{- if .Values.caCert }}
         # HTTPS Inspection 
            - name: CA_CERT
              value: /home/node/cacert/{{ .Values.caCert }}
         {{- end }}
         {{- if .Values.httpsCert }}
         # HTTPS Config
            - name: HTTPS_CERT
              value: /home/node/httpscert/{{ .Values.httpsCert }}
         {{- end }}
         {{- if .Values.httpsKey }}
            - name: HTTPS_KEY
              value: /home/node/httpskey/{{ .Values.httpsKey }}
         {{- end }}

{{- if or .Values.caCert .Values.httpsCert .Values.httpsKey  }}   
      volumes:
      {{- if .Values.caCert }}
      - name: {{ include "snyk-broker.fullname" . }}-cacert-volume
        configMap:
          name: {{ include "snyk-broker.fullname" . }}-cacert-configmap
      {{- end }}
      {{- if .Values.httpsCert }}
      - name: {{ include "snyk-broker.fullname" . }}-httpscert-volume
        configMap:
          name: {{ include "snyk-broker.fullname" . }}-httpscert-configmap
      {{- end }}
      {{- if .Values.httpsKey }}
      - name: {{ include "snyk-broker.fullname" . }}-httpskey-volume
        configMap:
          name: {{ include "snyk-broker.fullname" . }}-httpskey-configmap
      {{- end }}
      
      {{- end }}
           
---                     
apiVersion: v1
kind: Service
metadata:
  name: "code-agent-service"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.caType }}
  ports:
    - port: {{ .Values.deployment.container.caSnykPort }}
      targetPort: {{ .Values.deployment.container.caSnykPort}}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-ca
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- end }}