{{- if .Values.crEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snyk-broker.fullname" . }}-cr-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "snyk-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "snyk-broker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "snyk-broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
         # Container Registry Agent
          image: "{{ .Values.image.repository }}:{{ .Values.crImage}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.container.crContainerPort }}
          env:
            - name: BROKER_TOKEN
              value: {{ .Values.brokerToken }}
            - name: CR_AGENT_URL
              value: {{ .Values.crAgentUrl }}
            - name: CR_CREDENTIALS
              value: {{ .Values.crCredentials }}       
            - name: PORT
              value: {{ .Values.deployment.container.containerPort | squote }}
            - name: BROKER_CLIENT_URL
              value: {{ .Values.brokerClientUrl }}
          {{- end }}