# Default values for snyk-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Snyk Specific Values
brokerToken: ""
brokerClientUrl: ""

# SCM Generic
scmType: "github-com"
scmToken: ""

# Github Enterprise
github: ""
githubApi: ""
githubGraphQl: ""

# Bitbucket Server 
bitbucketUsername: ""
bitbucketPassword: ""
bitbucket: ""
bitbucketApi: "" 

# GitLab
gitlab: ""

# Azure Repos
azureReposOrg: ""
azureReposHost: ""

# Artifactory
artifactoryUrl: ""

# Jira
jiraUsername: ""
jiraPassword: ""
jiraHostname: ""

# Container Registry Broker
crType: ""
crBase: ""
crUsername: ""
crPassword: ""
crImage: "latest"

# Code Agent
enableCodeAgent: ""
snykToken: ""
caImage: "latest"
gitClientUrl: ""

# Logging
logLevel: "info"
logEnableBody: "false"

# Advanced
httpsCert: ""
httpsKey: ""
caCert: ""
tlsRejectUnauthorized: "" 

# Specify an accept.json file already present on the container image.
accept: ""

# Specify a local accept.json file (relative to snyk-broker folder) to inject with a ConfigMap, e.g. "files/accept.json"
acceptJsonFile: ""

image:
  repository: snyk/broker
  crRepository: snyk/container-registry-agent
  caRepository: snyk/code-agent
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

brokerResources:
   limits:
     cpu: 1
     memory: "256Mi"
   requests:
     cpu: 1
     memory: "256Mi"

crResources:
   limits:
     cpu: 1
     memory: "2Gi"
   requests:
     cpu: 1
     memory: "2Gi"

caResources:
   limits:
     cpu: 1
     memory: "2Gi"
   requests:
     cpu: 1
     memory: "2Gi"

#Container port for Snyk Broker
deployment:
   container: 
     containerPort: 8000
     crSnykPort: 8081
     caSnykPort: 3000
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "snyk-broker"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: true
   allowPrivilegeEscalation: false
   runAsNonRoot: true
   runAsUser: 1000

securityContextCr: 
   capabilities:
     drop:
     - ALL
   allowPrivilegeEscalation: false
   runAsNonRoot: true
   runAsUser: 1000

securityContextCa: 
   capabilities:
     drop:
     - ALL
   allowPrivilegeEscalation: false
   runAsNonRoot: true
   runAsUser: 1000


# Enable Ingress
enableIngress: false
ingressHostname: ""

service:
  #Snyk Broker
  brokerType: ClusterIP
  crType: ClusterIP
  caType: ClusterIP
  port: 8000


  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


